### ISSUE TITLE
How do i use the orchestration service from my local machine?

### ISSUE THREAD

**Issue by Thilaknath** [SAP/ai-sdk-js#382]
### Describe the Question

I have a deployment of SAP AI Core in Canary landscape. I have the orchestration deployment url and was able to invoke the API's from Bruno. 

I am unable to interact with the sdk at all. I set the environment variable with my downloaded service key. I get the following error. 
```
[2024-12-18T23:57:57.104Z] INFO     (context): Found a service key in environment variable "AICORE_SERVICE_KEY". Using a service key is recommended for local testing only. Bind the AI Core service to the application for productive usage.
[2024-12-18T23:57:57.110Z] WARN     (client-credentials-token-cache): Cannot create cache key for client credentials token cache. The given client ID is undefined.
```

It would be clearer if the documentation contains some examples. I did not face similar issues while using python sdk. Can you please help. What this error is ?

This is my simple program which I am trying to invoke 

```
import { OrchestrationClient } from '@sap-ai-sdk/orchestration';

const orchestrationClient = new OrchestrationClient({
  llm: {
    model_name: 'gpt-4-32k',
    model_params: { max_tokens: 50, temperature: 0.1 }
  },
  templating: {
    template: [
      { role: 'user', content: 'What is the capital of {{?country}}?' }
    ]
  }
});

const response = await orchestrationClient.chatCompletion({
  inputParams: { country: 'France' }
});

const responseContent = response.getContent();
console.log(responseContent);
```

**Comment by KavithaSiva** [comment]
Hi @Thilaknath,

Thanks for reaching out to us.

I tried reproducing your issue, and only got the error you mentioned if I don't have a `clientid` in my service key.
Do you have this entry in the local environment variable you set up?

Internally for our testing, we use `.env` file and use `dotenv` to load the file programattically.
You can maybe try this approach.

Please note while setting up the environment variable file, you should use single quote outside the JSON values and double quotes for values inside the JSON.

```
AICORE_SERVICE_KEY='{
   "clientid": "<your-value>", ...
}'
``` 
We do document the usage of the Orchestration client in [npm](https://www.npmjs.com/package/@sap-ai-sdk/orchestration#usage) and also in our [readme](https://github.com/SAP/ai-sdk-js/blob/main/packages/orchestration/README.md).

We also have a [sample](https://github.com/SAP/ai-sdk-js/blob/main/sample-code/src/orchestration.ts), which illustrates different ways of consuming the orchestration client.


Regards,
Kavitha

**Comment by Thilaknath** [comment]
Hello @KavithaSiva @ZhongpinWang 
I cloned the sample code repository and have set a .env file following the instruction from the README.md. Please find attached the screenshot of my .env <img width="339" alt="Image" src="https://github.com/user-attachments/assets/1282d3e5-4652-47bd-8e39-647d7699016a" />

Upon following instructions to start the service using `pnpm local`. The service starts. But when I do a request to the service running locally. It crashes and these are the logs were similar to the one where I tried to execute a standalone invocation. Can you please advise?

I am running on a Macbook M1 machine with zsh terminal. Logs below
```
(node:95557) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:95557) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
Server running at http://localhost:8080
[2024-12-19T13:49:32.634Z] INFO     (context): Found a service key in environment variable "AICORE_SERVICE_KEY". Using a service key is recommended for local testing only. Bind the AI Core service to the application for productive usage.
[2024-12-19T13:49:32.640Z] WARN     (client-credentials-token-cache): Cannot create cache key for client credentials token cache. The given client ID is undefined.
ErrorWithCause: Could not fetch client credentials token for service of type "aicore".
    at serviceToken (/Users/machine/Documents/code/ai-sdk-js/node_modules/.pnpm/@sap-cloud-sdk+connectivity@3.24.0/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/token-accessor.js:46:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.aicoreToDestination [as aicore] (/Users/machine/Documents/code/ai-sdk-js/node_modules/.pnpm/@sap-cloud-sdk+connectivity@3.24.0/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/destination/service-binding-to-destination.js:57:19)
    ... 3 lines matching cause stack trace ...
    at async file:///Users/machine/Documents/code/ai-sdk-js/sample-code/src/server.ts:26:18
Caused by:
Error: Could not fetch client credentials token for service of type aicore: XsuaaService is missing the properties url inside its credentials for: fetch token via client secret authentication.
    at /Users/machine/Documents/code/ai-sdk-js/node_modules/.pnpm/@sap-cloud-sdk+connectivity@3.24.0/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/xsuaa-service.js:40:15
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async serviceToken (/Users/machine/Documents/code/ai-sdk-js/node_modules/.pnpm/@sap-cloud-sdk+connectivity@3.24.0/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/token-accessor.js:39:23)
    at async Object.aicoreToDestination [as aicore] (/Users/machine/Documents/code/ai-sdk-js/node_modules/.pnpm/@sap-cloud-sdk+connectivity@3.24.0/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/destination/service-binding-to-destination.js:57:19)
    at async getAiCoreDestination (file:///Users/machine/Documents/code/ai-sdk-js/packages/core/dist/context.js:36:32)
    at async executeRequest (file:///Users/machine/Documents/code/ai-sdk-js/packages/core/dist/http-client.js:13:31)
    at async OpenApiRequestBuilder.execute (file:///Users/machine/Documents/code/ai-sdk-js/packages/core/dist/openapi-request-builder.js:37:26)
    at async file:///Users/machine/Documents/code/ai-sdk-js/sample-code/src/server.ts:26:18 {
  cause: Error: Could not fetch client credentials token for service of type aicore: XsuaaService is missing the properties url inside its credentials for: fetch token via client secret authentication.
      at /Users/machine/Documents/code/ai-sdk-js/node_modules/.pnpm/@sap-cloud-sdk+connectivity@3.24.0/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/xsuaa-service.js:40:15
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async serviceToken (/Users/machine/Documents/code/ai-sdk-js/node_modules/.pnpm/@sap-cloud-sdk+connectivity@3.24.0/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/token-accessor.js:39:23)
      at async Object.aicoreToDestination [as aicore] (/Users/machine/Documents/code/ai-sdk-js/node_modules/.pnpm/@sap-cloud-sdk+connectivity@3.24.0/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/destination/service-binding-to-destination.js:57:19)
      at async getAiCoreDestination (file:///Users/machine/Documents/code/ai-sdk-js/packages/core/dist/context.js:36:32)
      at async executeRequest (file:///Users/machine/Documents/code/ai-sdk-js/packages/core/dist/http-client.js:13:31)
      at async OpenApiRequestBuilder.execute (file:///Users/machine/Documents/code/ai-sdk-js/packages/core/dist/openapi-request-builder.js:37:26)
      at async file:///Users/machine/Documents/code/ai-sdk-js/sample-code/src/server.ts:26:18
}
[2024-12-19T13:49:32.648Z] ERROR    TypeError: Cannot read properties of undefined (reading 'data')
    at file:///Users/machine/Documents/code/ai-sdk-js/sample-code/src/server.ts:30:41
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

**Comment by ZhongpinWang** [comment]
Hi @Thilaknath ,

The format for JS SDK is different from python. Please use the original json obtained from AI Core service binding.

```
AICORE_SERVICE_KEY='{"clientid":"...","clientsecret":"...","url":"...","serviceurls":{"AI_API_URL":"..."}}'
```

**Comment by Thilaknath** [comment]
@ZhongpinWang  Thank you that works. The service starts up fine. If I want to execute a standalone script like the one below. 

```
import { OrchestrationClient } from '@sap-ai-sdk/orchestration';

const orchestrationClient = new OrchestrationClient({
  llm: {
    model_name: 'gpt-4-32k',
    model_params: { max_tokens: 50, temperature: 0.1 }
  },
  templating: {
    template: [
      { role: 'user', content: 'What is the capital of {{?country}}?' }
    ]
  }
});

const response = await orchestrationClient.chatCompletion({
  inputParams: { country: 'France' }
});

const responseContent = response.getContent();
console.log(responseContent);
```

I get the error `Error: No deployment matched the given criteria: {"scenarioId":"orchestration"}` 

Can you advice, what am I missing ?  Can i influence passing the RESOURCE_GROUP where my orchestration deployment is currently in ?

**Comment by jjtang1985** [comment]
I'll close this issue, as the answer was provided.
Please reopen, if needed.
